services:
  lldap:
    image: lldap/lldap:stable
    container_name: lldap
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      UID: 1000
      GID: 1000
      LLDAP_JWT_SECRET: ${LLDAP_JWT_SECRET}
      LLDAP_KEY_SEED: ${LLDAP_KEY_SEED}
      LLDAP_LDAP_BASE_DN: ${LLDAP_LDAP_BASE_DN}
      LLDAP_LDAP_USER_DN: admin
      LLDAP_LDAP_USER_EMAIL: ${LLDAP_LDAP_USER_EMAIL}
      LLDAP_LDAP_USER_PASS: ${LLDAP_LDAP_USER_PASS}
      LLDAP_HTTP_URL: https://${LLDAP_HOST}:8443
    volumes:
      - lldap_data:/data
    networks:
      - proxy
      - auth-backend

  authelia:
    image: authelia/authelia:4.38
    container_name: authelia
    restart: unless-stopped
    depends_on:
      lldap:
        condition: service_healthy
    environment:
      TZ: ${TZ}
      AUTHELIA_JWT_SECRET: ${AUTHELIA_JWT_SECRET}
      AUTHELIA_SESSION_SECRET: ${AUTHELIA_SESSION_SECRET}
      AUTHELIA_STORAGE_ENCRYPTION_KEY: ${AUTHELIA_STORAGE_ENCRYPTION_KEY}
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: ${LLDAP_LDAP_USER_PASS}
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET: ${AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET}
    volumes:
      - ./infra/authelia:/config
    networks:
      - proxy
      - auth-backend

volumes:
  lldap_data:

networks:
  proxy:
    external: true
  auth-backend:
    driver: bridge
