services:
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: facturation-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5173
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.frontend.rule=Host(`${HOST}`)
      - traefik.http.routers.frontend.entrypoints=websecure
      - traefik.http.routers.frontend.tls=true
      - traefik.http.routers.frontend.priority=1
      - traefik.http.routers.frontend.middlewares=authelia@docker
      - traefik.http.routers.frontend.service=frontend
      - traefik.http.services.frontend.loadbalancer.server.port=5173

networks:
  proxy:
    external: true
