name: facturation

services:
  traefik:
    image: traefik:v3.5
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command:
      - --api.dashboard=true
      - --providers.file.filename=/etc/traefik/dynamic.yml
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./infra/traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./infra/traefik/certs:/certs:ro
    networks:
      - proxy

networks:
  proxy:
    external: true
