theme: light

server:
  address: tcp://0.0.0.0:9091/auth
  endpoints:
    authz:
      forward-auth:
        implementation: ForwardAuth

log:
  level: info

totp:
  disable: true

authentication_backend:
  refresh_interval: 1m
  password_reset:
    disable: true
  ldap:
    implementation: lldap
    address: ldap://lldap:3890
    timeout: 5s
    start_tls: false
    base_dn: dc=facturation,dc=test
    additional_users_dn: ou=people
    additional_groups_dn: ou=groups
    user: uid=admin,ou=people,dc=facturation,dc=test

access_control:
  default_policy: deny
  rules:
    - domain: admin.facturation.test
      policy: one_factor
      subject:
        - group:lldap_admin
        - group:admins
    - domain: traefik.facturation.test
      policy: one_factor
      subject:
        - group:lldap_admin
        - group:admins
    - domain: app.facturation.test
      policy: one_factor

session:
  name: authelia_session
  same_site: lax
  inactivity: 1h
  expiration: 12h
  remember_me: 1M
  cookies:
    - domain: facturation.test
      authelia_url: https://app.facturation.test/auth
      default_redirection_url: https://app.facturation.test/

regulation:
  max_retries: 5
  find_time: 2m
  ban_time: 10m

storage:
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notifications.txt
